print("Assign the value for a and b")
print("Enter the first number:")
x = input()
print("Enter the second number:")
y = input()
a = int(x)
b = int(y)
print("sum:", a + b)
print("different:", a - b)
print("product:", a * b)
quotient = float(x) / float(b)
print("quotient:", quotient)